# Generated by Django 5.2.4 on 2025-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
