# Generated by Django 5.2.4 on 2025-10-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_endpoint_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='script',
        ),
    ]
