# Generated by Django 5.2.4 on 2025-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0003_remove_endpoint_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='response_image',
            field=models.ImageField(blank=True, null=True, upload_to='endpoint_images/'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_redirect_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_type',
            field=models.CharField(choices=[('NOT_FOUND', 'Not Found'), ('REDIRECT', 'Redirect'), ('IMAGE', 'Image')], default='NOT_FOUND', max_length=20),
        ),
    ]
