# Generated by Django 5.2.4 on 2025-10-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0004_endpoint_response_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiver.endpoint'),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
