# Generated by Django 5.2.4 on 2025-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0005_alter_apicall_endpoint_alter_apicall_remote_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='response_image_referer_failure',
            field=models.ImageField(blank=True, null=True, upload_to='endpoint_images/'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_image_referer_success',
            field=models.ImageField(blank=True, null=True, upload_to='endpoint_images/'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_referer_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='response_type',
            field=models.CharField(choices=[('NOT_FOUND', 'Not Found'), ('REDIRECT', 'Redirect'), ('IMAGE', 'Image'), ('REFERER', 'Referer')], default='NOT_FOUND', max_length=20),
        ),
    ]
