# Generated by Django 5.2.4 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0006_endpoint_response_image_referer_failure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='referer_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
